@baseUrl = http://localhost:4004/odata/v4/movie-studio

### ------------------------------------------------------------------------
Get {{baseUrl}}/ShowHighBudgetFilms
###

### ------------------------------------------------------------------------
POST {{baseUrl}}/ChangeFilmDirector
Content-Type: application/json

{
    "filmID": "FILM_UUID_1",
    "directorID" : "PERSON_UUID_1"
}
###

### ------------------------------------------------------------------------
POST {{baseUrl}}/ChangeFilmDirector
Content-Type: application/json

{
    "filmID": "FILM_UUID_1",
    "directorID" : "PERSON_UUID_2"
}
###

### ------------------------------------------------------------------------
POST {{baseUrl}}/ChangeFilmDirector
Content-Type: application/json

{
    "filmID": "FILM_UUID_1",
    "directorID" : "PERSON_UUID_100"
}
###

### ------------------------------------------------------------------------
GET {{baseUrl}}/FilmTitle(filmID='FILM_UUID_1')/Set
###

### ------------------------------------------------------------------------
Get {{baseUrl}}/Films
###

### ------------------------------------------------------------------------
PATCH {{baseUrl}}/Films('FILM_UUID_1')
Content-Type: application/json

{  
    "director_ID":"PERSON_UUID_3"
}
###

### ------------------------------------------------------------------------
Get {{baseUrl}}/sleep()
###

@baseUrl = http://localhost:4004

### ------------------------------------------------------------------------
Get {{baseUrl}}/films/sleep()
###

### ------------------------------------------------------------------------
GET {{baseUrl}}/films/FilmsByTitleView(title='Titanic')/Set
###

### ------------------------------------------------------------------------
GET {{baseUrl}}/films/GetFilmsByDuration(duration=100)
###

### ------------------------------------------------------------------------
GET {{baseUrl}}/schedules/GetSchedules
###

### ------------------------------------------------------------------------
POST {{baseUrl}}/schedules/AddSchedule
Content-Type: application/json

{
    "film": 1,
    "crew": 1,
    "location": 1,
    "shoots": [
        {
            "startDate": "2000-05-01",
            "endDate": "2000-05-02",
            "description": "test"
        }
    ]
}
###

@baseUrl = https://e4224610trial-dev2-movie-studio-srv.cfapps.us10-001.hana.ondemand.com

### ------------------------------------------------------------------------
GET {{baseUrl}}/schedules/GetSchedules
###
